services:
  postgres:
    image: 'postgres:16.1'
    container_name: 'movies-for-back'
    environment:
      - 'POSTGRES_DB=movie-recommendation'
      - 'POSTGRES_PASSWORD=francisco2525'
      - 'POSTGRES_USER=fran'
    ports:
      - '5432:5432'
    volumes:
      - pg-movies-data:/var/lib/postgresql/data
volumes:
  pg-movies-data:
    external: true